unstable_features = true

wrap_comments = true
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
match_block_trailing_comma = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
